[package]
name = "ld54"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = "s"               # Use slightly better optimizations.
lto = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4.4"
